id = "zed-simple-dark-theme"
name = "Simple Dark Theme"
version = "0.0.1"
schema_version = 1
authors = ["luantran069 <luantran.dev069@gmail.com>"]
description = "Simple Dark Theme"
repository = "https://github.com/luantran069/zed-simple-dark-theme"